apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: myvotingapp
spec:
  type: LoadBalancer
  selector:
    name: result-pod
  ports:
    - port: 80
      targetPort: 80
