apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: myresultapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-pod
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-pod
        app: myvotingapp
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
