apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: myvotingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: vote-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: vote-pod
        app: myvotingapp
    spec:
      containers:
        - name: voting
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
