apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: myworkingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-pod
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-pod
        app: myvotingapp
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
